Add PNG development output
Kartoffel/infodisplay pull request #3
Opened 2023-01-13 23:22 UTC by jelly

This PR adds a new config option which if set to `display_class = display_png`  is useful for local development where a `display.png` is written on every draw. This is useful for local development without an e-ink monitor.

2023-01-14 08:20 UTC, Kartoffel requested changes
Super useful feature, thanks!
I've added some feedback to your commit, please inspect :)

2023-01-14 08:20 UTC, Kartoffel commented on config.ini.example
> +display_class = display
This option is named `display`, see [`run,py`, line 45](https://github.com/Kartoffel/infodisplay/pull/3/commits/962e020cf0729cd311cbfb2087d729856990292b#diff-d6af0459a37d985953d7040c14f53feb3b9cc9e58b543aa3c2b80256d276c5e0R45).

2023-01-14 08:20 UTC, Kartoffel commented on display_png.py
> +        self.width = 800
Yes please, let's move width and height to config parameters.
The default display class gets the width and height of the display automatically, so the config parameters should be optional. Width 800 and height 600 seems like sensible defaults.

2023-01-16 19:11 UTC, jelly commented on config.ini.example
> +display_class = display
I'll make it `display_class` as `display` is a bit ambigious.

2023-01-19 20:22 UTC, Kartoffel approved these changes
Looks good, thanks!

2023-01-19 20:24 UTC, merged